### ISSUE TITLE
GNOME 桌面环境下 QQ 频道功能与 xdg-desktop-portal-gnome 的兼容性问题

### ISSUE THREAD

**Issue by taoky** [flathub/com.qq.QQ#12]
打开频道功能时，QQ 似乎会多次打开以 "jsbridge://" 开头的 URL，在 Flatpak 环境下会触发 portal 的 `org.freedesktop.portal.OpenURI.OpenURI`。GNOME 桌面环境下 `xdg-desktop-portal-gnome` 会弹出大量的「未找到应用」的弹窗。

![Screenshot from 2022-12-31 02-38-16](https://user-images.githubusercontent.com/2109893/210126427-ef81b8ef-f6b2-42d2-a8e9-8a1c07998e00.png)

![Screenshot from 2022-12-31 02-38-05](https://user-images.githubusercontent.com/2109893/210126423-90116d19-40c2-4267-ac90-662dfb29eb3c.png)

并且在后台（最小化）每运行一段时间，QQ 似乎都会再去访问 "jsbridge://" 的 URL，导致用户被弹窗打扰。

我没有找到能让启动的程序使用其他 portal 的方法，Flatpak 目前[亦不提供关闭 portal 的选项](https://github.com/flatpak/flatpak/issues/3977)。

**Comment by taoky** [comment]
一个可能有效的 workaround:

1. 创建 `~/.local/share/applications/JSBridge.desktop` 如下：

   ```
   [Desktop Entry]
   Name=JSBridge
   Exec=echo %u
   Type=Application
   Terminal=false
   MimeType=x-scheme-handler/jsbridge;
   ```
2. 可能需要运行 `sudo update-desktop-database`
3. 编辑 `~/.config/mimeapps.list`，在 `[Default Applications]` 里加入 `x-scheme-handler/jsbridge=JSBridge.desktop`，在 `[Added Associations]` 里加入 `x-scheme-handler/jsbridge=JSBridge.desktop;`
4. 验证：以下命令 portal 不弹出窗口

    ```
    gdbus call --session \
        --dest org.freedesktop.portal.Desktop \
        --object-path /org/freedesktop/portal/desktop \
        --method org.freedesktop.portal.OpenURI.OpenURI \
        "" "jsbridge://114514" {}
    ```

这么做 Applications 里面会多出一个 JSBridge，把它拖到文件夹里让它看不到就行（

**Comment by ZhaoZuohong** [comment]
@taoky  在desktop entry里加上一行`NoDisplay=true`就可以不显示了

**Comment by chenzhiwei** [comment]
谁能提个PR不？我手机操作不方便。

**Comment by xz-dev** [comment]
> 谁能提个PR不？我手机操作不方便。

具体应该要 PR 什么呢

**Comment by neovali** [comment]
#19 似乎把这个问题也解决了

**Comment by chenzhiwei** [comment]
该问题已经解决
