### ISSUE TITLE
Distribute icon with the app

### ISSUE THREAD

**Issue by barthalion** [flathub/com.qq.QQ#2]
beta.flathub.org doesn't support remote icons, and at some point CI will reject builds if the icon is not shipped with the app.

**Comment by chenzhiwei** [comment]
Hi @barthalion , I distributed the app icon locally, but there is no icon in flathub page: https://flathub.org/apps/details/com.qq.QQ

Do you know the reason?

**Comment by catsout** [comment]
@chenzhiwei 
https://docs.flatpak.org/en/latest/freedesktop-quick-reference.html  

app icon should be installed to `/app/share/icons/hicolor/$size/apps/`.   

size requirements:   
at least one of 128/256/512  
square size

**Comment by catsout** [comment]
Remote icon can avoid icon checking.    
But as barthalion said, it's not recommended now.

**Comment by chenzhiwei** [comment]
The icon check will fail when putting it to this directory:

> app icon should be installed to /app/share/icons/hicolor/$size/apps/.

**Comment by chenzhiwei** [comment]
fixed in #7
