### ISSUE TITLE
[BUG] 手机QQ向Linux QQ发送文件时，Linux QQ端无法接收文件

### ISSUE THREAD

**Issue by asuka909** [flathub/com.qq.QQ#33]
Linux QQ 版本 : 3.2.0-16736
系统信息 : 
![图片](https://github.com/flathub/com.qq.QQ/assets/64319186/f7a85a80-489d-4fc9-b767-b9811ad7c5fb)

表现 : Linux QQ 无法接收任何文件。另存为也无法保存至 `xdg-download` 文件夹。

复现步骤 :
1. 使用 Android QQ 在 我的电脑 对话框中向 Linux QQ 发送任意文件。
2. 使用Linux QQ在电脑上点击下载。

设置->存储管理 中可以正确识别宿主机的下载目录。
![图片](https://github.com/flathub/com.qq.QQ/assets/64319186/6f6cacab-99c1-47c4-812e-d4a1d08fd4f4)

`~/.var/app/com.qq.QQ/config/QQ/nt_qq_xxxxxxxxxxxxxxxxxxxxxx/nt_data/dataline/.tmp/` 文件夹中产生了临时文件。

UPDATE: 从Andorid 手机、IPad 发送的文件均无法接收。

**Comment by asuka909** [comment]
破案了 Linux QQ 调用了 rename() 来把文件从移动临时文件到下载目录，然而 rename() 不支持跨文件系统移动。
workaround是把QQ下载文件夹改到~/.var/app/com.qq.QQ/data/下。
解决办法：等腾讯修复。。。。
![图片](https://github.com/flathub/com.qq.QQ/assets/64319186/5d6bec8e-3f70-4569-95fc-fbc3160b5d27)

**Comment by chenzhiwei** [comment]
给腾讯提bug了没？

**Comment by asuka909** [comment]
> 给腾讯提bug了没？

我开了个PR，可以用LD_PRELOAD替换掉rename()的实现。我估计腾讯不会修的。这个不能算bug，flatpak也不是腾讯支持的分发渠道。

**Comment by chenzhiwei** [comment]
should be fixed in https://github.com/flathub/com.qq.QQ/pull/45
