### ISSUE TITLE
Bug合集，频道窗口问题和系统托盘问题

### ISSUE THREAD

**Issue by MomentQYC** [flathub/com.qq.QQ#61]
系统Debian 12，GNOME 43，Wayland

频道单独的窗口在打开一段时间后会无法关闭，只能通过使QQ进程结束关闭

系统托盘的QQ图标只能双击打开QQ，右键不起作用

如果需要什么额外的信息，我会进行补充

**Comment by SamLukeYes** [comment]
托盘的问题我在 NixOS 上也有遇到，现在是 GNOME 45，以前 GNOME 44 的时候也有这个问题，目前我的 workaround 是每次启动 QQ 后关闭再重新打开 appindicator 扩展

**Comment by madoka773** [comment]
无解，等qq修

**Comment by karman011** [comment]
```shell
flatpak override --no-talk-name=org.kde.StatusNotifierWatcher com.qq.QQ
```

**Comment by MomentQYC** [comment]
> > 频道单独的窗口在打开一段时间后会无法关闭，只能通过使QQ进程结束关闭
> 
> 使用deb、rpm或appimage有一样的行为吗？

deb之前在一个基于Ubuntu 20.04的系统上面运行正常，另外的两个没试过
这个系统不打算装原生QQ

**Comment by MomentQYC** [comment]
> > > > 频道单独的窗口在打开一段时间后会无法关闭，只能通过使QQ进程结束关闭
> > > 
> > > 
> > > 使用deb、rpm或appimage有一样的行为吗？
> > 
> > 
> > deb之前在一个基于Ubuntu 20.04的系统上面运行正常，另外的两个没试过
> > 这个系统不打算装原生QQ
> 
> 你能提供具体的复现步骤吗？我昨天测试了一会，无法复现。GNOME45，Fedora 39。

经过多次测试，这个问题似乎在最新的flatpak包被修复

**Comment by karman011** [comment]
托盘问题不是 flatpak 问题。请反馈给gnome拓展上游。@MomentQYC 这个issue可以关了。
