### ISSUE TITLE
QQ 的 x-checker-data.pattern 已经过期

### ISSUE THREAD

**Issue by arenekosreal** [flathub/com.qq.QQ#76]
当前的 `x-checker-data.pattern` 在 amd64 和 arm64 上分别是 `(https://[^"]+/linuxqq_([\d\.\-]+)_amd64.deb)` 和 `(https://[^"]+/linuxqq_([\d\.\-]+)_arm64.deb)`，已经不能匹配到正确的更新地址。可考虑换成 `(https://[^"]+/QQ_([\d\.\-]+)_amd64_01.deb)` 和 `(https://[^"]+/QQ_([\d\.\-]+)_arm64_01.deb)`

**Comment by madoka773** [comment]
未必

**Comment by lzq960605** [comment]
Error: Extra data https://dldir1.qq.com/qqfile/qq/QQNT/e619e933/linuxqq_3.2.6-22165_amd64.deb has wrong size
