### ISSUE TITLE
当前版本仅限内部体验使用/设备存在风险？

### ISSUE THREAD

**Issue by mikotorz** [flathub/com.qq.QQ#8]
Fedora Workstation 37, GNOME 43.2, 6.0.15-300.fc37.x86_64.
扫码提示当前版本仅限内部体验使用，账密登陆扫码验证首次成功，退出后再次登陆提示设备存在风险。
是否为内测版本误上架？

**Comment by NEOVALI** [comment]
现在已经正式发布

**Comment by chenzhiwei** [comment]
3.0.0 正式版已经发布。
