### ISSUE TITLE
请更新3.2.7版本

### ISSUE THREAD

**Issue by lzq960605** [flathub/com.qq.QQ#82]
https://dldir1.qq.com/qqfile/qq/QQNT/1e486dc4/linuxqq_3.2.7-22578_amd64.deb

**Comment by chenzhiwei** [comment]
最近QQ下载页面的下载链接格式有所调整，导致flathub bot无法自动获取。请稍等。

**Comment by chenzhiwei** [comment]
fixed in https://github.com/flathub/com.qq.QQ/pull/83
