### ISSUE TITLE
QQ 内置表情无法加载，疑似官方 deb 版本本身就不能加载

### ISSUE THREAD

**Issue by peiyuanix** [flathub/com.qq.QQ#85]
在 Ubuntu 24.04 测试了 QQ_3.2.7_240422_amd64_01.deb 和 QQ_3.2.7_240410_amd64_01.deb 两个版本，聊天界面点击表情图标，一个表情都不会显示，甚至没有表情占位符，无法选择表情。聊天消息中的表情显示为表情占位符。

收藏的图片表情不受影响。

没搜到相关消息，想确认下大家是否有同样问题。

![image](https://github.com/flathub/com.qq.QQ/assets/11792595/69398934-0415-44ee-bddc-e27d5d1ba25f)

**Comment by peiyuanix** [comment]
UPDATE：3.2.6 最后一个版本是正常的 <https://dldir1.qq.com/qqfile/qq/QQNT/Linux/QQ_3.2.6_240322_amd64_01.deb>，
新发布的 3.2.7 两个版本都不正常。

**Comment by madoka773** [comment]
没有这个问题

**Comment by madoka773** [comment]
![image](https://github.com/flathub/com.qq.QQ/assets/85693457/66d879e9-7ad2-4316-a1f7-585b20e73fe0)

**Comment by peiyuanix** [comment]
@madoka773 感谢，根据这个线索我又测了一下，从我的 3.2.6 升级版本上来是没问题的。

所以结论就是：可能 3.2.7 无法正确下载 QQ 表情数据，所以直接安装  QQ_3.2.7_240422_amd64_01.deb 或 QQ_3.2.7_240410_amd64_01.deb 均无法正常显示表情。

一种 workaround 是：先安装 3.2.6，登录账号，让 QQ 下载好表情数据。然后保留数据升级到 3.2.7 版本。

**Comment by madoka773** [comment]
> @madoka773 感谢，根据这个线索我又测了一下，从我的 3.2.6 升级版本上来是没问题的。
> 
> 所以结论就是：可能 3.2.7 无法正确下载 QQ 表情数据，所以直接安装 QQ_3.2.7_240422_amd64_01.deb 或 QQ_3.2.7_240410_amd64_01.deb 均无法正常显示表情。
> 
> 一种 workaround 是：先安装 3.2.6，登录账号，让 QQ 下载好表情数据。然后保留数据升级到 3.2.7 版本。

我全新安装的3.2.7也没问题

**Comment by madoka773** [comment]
> @madoka773 感谢，根据这个线索我又测了一下，从我的 3.2.6 升级版本上来是没问题的。
> 
> 所以结论就是：可能 3.2.7 无法正确下载 QQ 表情数据，所以直接安装 QQ_3.2.7_240422_amd64_01.deb 或 QQ_3.2.7_240410_amd64_01.deb 均无法正常显示表情。
> 
> 一种 workaround 是：先安装 3.2.6，登录账号，让 QQ 下载好表情数据。然后保留数据升级到 3.2.7 版本。

另外这是flatpak ，你这根本算不上是workaround

**Comment by peiyuanix** [comment]
我又测了一下，在 Ubuntu 22.04 上直装 3.2.7 0422 deb 包是正常的。

昨天是在 Ubuntu 24.04 上测试 3.2.7 0422 deb 包，无法显示 QQ 表情。

在 NixOS 23.11 上用 flatpak 打包 3.2.7 也无法正常显示 QQ 表情。先打包一个 3.2.6 安装好启动并登录，可以正常显示。然后打包一个 3.2.7，并保留数据升级上去，QQ 表情也是正常的。

有类似情况的可以参考。

我这边是自己 build 的 flatpak 包，所以各个版本都能安装，在 flatpak 上指定版本安装确实比较困难，我不清楚如何安装。

**Comment by peiyuanix** [comment]
又在 Ubuntu 24.04 上试了一下 Flatpak 版本，第一次登录无法显示，第二次登录又好了。
DEB 版本下载好直接就是正常的，可能是可能是我网络问题或者 QQ 表情资源下载功能不稳定，不是 3.2.7 本身的问题。
NixOS 上 Flatpak 版本也正常了。
