### ISSUE TITLE
[Bug] Wayland 检测在某些设备上出现问题

### ISSUE THREAD

**Issue by arenekosreal** [flathub/com.qq.QQ#87]
不确定是否根据 flatpak 版本不同而有不同的行为。我有一个设备运行着 ArchLinux，它的 `flatpak --version` 输出为 `Flatpak 1.15.8`，在 Wayland 会话执行时无法正常启动，终端输出带有这两行：
```
[2:0502/202054.610571:ERROR:ozone_platform_x11.cc(240)] Missing X server or $DISPLAY
[2:0502/202054.610587:ERROR:env.cc(257)] The platform failed to initialize.  Exiting.
```
似乎是检测 Wayland 出现问题了。
执行 `flatpak run --command=sh --socket=wayland com.qq.QQ` 后在 shell 中检查 `$WAYLAND_DISPLAY` 环境变量发现其值是 `/run/flatpak/wayland-0` 而不是 `wayland-0`，所以导致对 Wayland 的检查出现问题。建议将 https://github.com/flathub/com.qq.QQ/blob/master/com.qq.QQ.yaml#L109 改为 `if [[ -e "$XDG_RUNTIME_DIR/${WAYLAND_SOCKET}" ]] || [[ -e "$WAYLAND_SOCKET" ]]` 以兼容这种 `$WAYLAND_DISPLAY` 为绝对路径的情况。

**Comment by arenekosreal** [comment]
另外考虑到 wayland-0 是一个 Socket，也许使用 `[[ -S "$XDG_RUNTIME_DIR/${WAYLAND_SOCKET}" ]] || [[ -S "WAYLAND_SOCKET" ]]` 更适合？

**Comment by saihaze** [comment]
我感觉无论是不是 Wayland 环境都可以加这些 flag
